### ISSUE TITLE
Print resume, curriculumVitae , coverLetter 

### ISSUE THREAD

**Issue by jjunghoo** [magatriod7/Final-Project#6]
## Tasks

- [x] Print resume and styling
- [x] Print resume_CurriculumVitae and styling
- [x] Print resume_CoverLetter and styling
